FROM debian:trixie

#Update trixie
RUN apt update && \

#Begin Software Install
apt install -y \
suricata \      
gettext-base \  
emacs \         
iproute2 
#End Software Install

#File Copying

#Service Specific
COPY ./suricata.yaml /etc/suricata/suricata.yaml
COPY ./.env /etc/suricata/.env

#Run export environment variables
#Replace Suricata.yaml variables with environment variables
#Generate Temp File
#Replace the old .yaml with the new one

RUN . /etc/suricata/.env && \
envsubst "$(sed -e 's/export /$/' -e 's/=[^=]*//' /etc/suricata/.env)" < /etc/suricata/suricata.yaml > /etc/suricata/suricata.yaml.tmp  && \
mv /etc/suricata/suricata.yaml.tmp /etc/suricata/suricata.yaml 

#Update suricata signatures
RUN suricata-update

#Remove ensubst since it is no longer needed.
RUN apt remove -y gettext-base

#Run suricata at container start
CMD ["/usr/bin/suricata -c /etc/suricata/suricata.yaml -i enp0s31f6"]

#Subnotes

#Software Categories

# Primary Service
# Suricata
# Supplemental Software: (To remain in the dockerfile but possibly removed at the end of the build)
# gettext-base: provides envsubst for substituting variables in config files with env variables
# "Fat" Software to be included in dev builds for testing but removed in live builds
# emacs: For File editing
# iproute2: for the "ip" command. Installed to check interface name.

