* Synopsis

Standard procedure for git commit messages.

* Procedure

1. Confirm the branch
2. Select the commit type from one of the following:

   feat: Commit which adds a new feature
   fix: Commit which fixes a bug
   refactor: refactored code that neither fixes a bug nor adds a feature but rewrites/restructures
             your code.
   chore : Changes that do not relate to a fix or feature and don’t modify src or test files
           "e.g.", updating dependencies, modifying .gitignore, renaming files or directories.
   perf : Commits which refactor for the purpose of improving performance.
   ci : Commits which are related to continous integration.
   ops : Commits, that affect operational components like infrastructure, deployment, backup ,
         recovery etc.
   build : Changes that affect the build system build tool, ci pipeline, dependencies, project
           version etc.
   docs : Commits whic affect the documentation, such as the README.
   style : changes that do not affect the meaning of the code, related to formatting
           such as white-space, missing semi-colons, etc.
   revert: Commits which revert a previous commit.
   test: commits which add missing tests or correct existing tests
   [fn:1]
   
* Footnotes

[fn:1] Source: https://medium.com/@iambonitheuri/the-art-of-writing-meaningful-git-commit-messages-a56887a4cb49 

* TODO Make a wrapper for git commit that presents the options listed here
